name: latest

on:
  push:
    paths-ignore:
      - '*.md'
      - LICENSE

  workflow_dispatch:

env:
  DOCKER_REGISTRY_NAME: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }} # takagi-minecraft-lab/paper

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.DOCKER_REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1